### ISSUE TITLE
Upgrade Spark to 2.0.1

### ISSUE THREAD

**Issue by ramhiser** [ramhiser/spark-kubernetes#5]
Spark 2.0.1 was [released](http://spark.apache.org/releases/spark-release-2-0-1.html) this week.
### TODO
- [x] Update `Dockerfile` with latest version
- [x] Update `README.md` to use 2.0.1
- [x] Push 2.0.1 tag to Docker hub
- [x] Update `latest` tag on Docker hub to use 2.0.1
